webtalk_init -webtalk_dir C:\\master\\EmbeddedPRJ\\SDcardExample\\SDcardExample.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-04 20:01:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vfbj698a36rb2rgju75m7nmrv8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1577769078915" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key hwid -value "1576503108683" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key bspid -value "1576503165100" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key projSize -value "1661.68359375" -context "sdk\\\\application/1577769078915"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key DebugCount -value "573" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key PerfCount -value "1" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578186102438"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578186102438"
webtalk_transmit -clientid 206931350 -regid "" -xml C:\\master\\EmbeddedPRJ\\SDcardExample\\SDcardExample.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\master\\EmbeddedPRJ\\SDcardExample\\SDcardExample.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\master\\EmbeddedPRJ\\SDcardExample\\SDcardExample.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
