# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/solution/solution.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution || ORIG_REF_NAME==solution}]

# IP: bd/solution/ip/solution_processing_system7_0_0/solution_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_processing_system7_0_0 || ORIG_REF_NAME==solution_processing_system7_0_0}]

# IP: bd/solution/ip/solution_axi_gpio_0_0/solution_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_axi_gpio_0_0 || ORIG_REF_NAME==solution_axi_gpio_0_0}]

# IP: bd/solution/ip/solution_Processor_axi_periph_0/solution_Processor_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_Processor_axi_periph_0 || ORIG_REF_NAME==solution_Processor_axi_periph_0}]

# IP: bd/solution/ip/solution_rst_Processor_100M_0/solution_rst_Processor_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_rst_Processor_100M_0 || ORIG_REF_NAME==solution_rst_Processor_100M_0}]

# IP: bd/solution/ip/solution_axi_gpio_0_1/solution_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_axi_gpio_0_1 || ORIG_REF_NAME==solution_axi_gpio_0_1}]

# IP: bd/solution/ip/solution_xbar_0/solution_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_xbar_0 || ORIG_REF_NAME==solution_xbar_0}]

# IP: bd/solution/ip/solution_auto_pc_0/solution_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==solution_auto_pc_0 || ORIG_REF_NAME==solution_auto_pc_0}]

# XDC: bd/solution/solution_ooc.xdc
